name: flutter_chat_ui_kit
description: CometChat Flutter UI Kit is a collection of custom UI Components
  designed to build text , chat  features in your application. The UI Kit is
  developed to keep developers in mind and aims to reduce development efforts
  significantly
version: 3.0.3-pluto.beta.1
homepage: https://www.cometchat.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  cached_network_image: ^3.2.3
  chewie: ^1.3.2
  cometchat: 3.0.3
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_image: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  http: ^0.13.4
  image_picker: ^0.8.5+1
  intl: ^0.17.0
  path_provider: ^2.0.9
  share_plus: ^6.2.0
  url_launcher: ^6.0.20
  video_player: ^2.2.17
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.cometchat.flutter_chat_ui_kit
        pluginClass: FlutterChatUiKitPlugin
      ios:
        pluginClass: FlutterChatUiKitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/sound/
    - assets/l10n/
    - assets/icons/
    - assets/icons/2x/
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
